/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Output;

import Koneksi.Koneksi;
import java.io.File;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author harip
 */
public class Form_Laporan_All extends javax.swing.JFrame {
    Connection connect;
    Statement state;
    ResultSet rs;
    PreparedStatement pr;

    /**
     * Creates new form Form_Laporan_ALL
     */
    public Form_Laporan_All() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_HORIZ);
        setVisible(true);
        setResizable (false);
        Tanggal_sekarang();
    }
    
            public void Tanggal_sekarang(){
        java.util.Date sekarang = new java.util.Date();
        java.text.SimpleDateFormat kal = new java.text.SimpleDateFormat ("yyyy-MM-dd") ;
        tanggal.setText(kal.format(sekarang));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txhari_donasi = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        bulanan_donasi = new javax.swing.JButton();
        txdonasii = new javax.swing.JTextField();
        txdonasi = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txhari_penjualan = new javax.swing.JTextField();
        harian_penjualan = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txhari_kas = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txkas = new javax.swing.JButton();
        harian_donasi = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txbulanan_kas = new javax.swing.JTextField();
        txbulanan_kass = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        bulanan_kas = new javax.swing.JButton();
        tanggal = new javax.swing.JLabel();
        txtbulan_penjualan = new javax.swing.JTextField();
        txtbulan_penjualann = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btsaran = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        btmenu = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1300, 720));
        setPreferredSize(new java.awt.Dimension(1300, 710));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txhari_donasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txhari_donasiActionPerformed(evt);
            }
        });
        getContentPane().add(txhari_donasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 220, 140, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Masukkan tanggal");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 490, -1, -1));

        jLabel3.setFont(new java.awt.Font("Forte", 1, 36)); // NOI18N
        jLabel3.setText("Data Laporan");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 40, 250, -1));

        bulanan_donasi.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        bulanan_donasi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Image 32pixel/printer.png"))); // NOI18N
        bulanan_donasi.setText(" Cetak Donasi");
        bulanan_donasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bulanan_donasiActionPerformed(evt);
            }
        });
        getContentPane().add(bulanan_donasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 280, 140, 40));

        txdonasii.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txdonasiiActionPerformed(evt);
            }
        });
        getContentPane().add(txdonasii, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 240, 130, 30));
        getContentPane().add(txdonasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 200, 130, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Masukkan tanggal");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 180, -1, 20));

        jLabel7.setFont(new java.awt.Font("Forte", 1, 24)); // NOI18N
        jLabel7.setText("Data Laporan Uang Kas");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 430, 270, -1));

        jLabel8.setFont(new java.awt.Font("Forte", 1, 24)); // NOI18N
        jLabel8.setText("Data Laporan Penjualan");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 120, 290, -1));
        getContentPane().add(txhari_penjualan, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 220, 130, 30));

        harian_penjualan.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        harian_penjualan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Image 32pixel/printer.png"))); // NOI18N
        harian_penjualan.setText("Cetak  Penjualan");
        harian_penjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                harian_penjualanActionPerformed(evt);
            }
        });
        getContentPane().add(harian_penjualan, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 290, 150, 40));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Masukkan tanggal");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 520, -1, 20));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Masukkan tanggal");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 200, -1, 20));

        jLabel5.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Laporan Harian", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 180, 180, 80));

        jButton8.setFont(new java.awt.Font("Gill Sans MT", 0, 17)); // NOI18N
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Image 32pixel/arrow.png"))); // NOI18N
        jButton8.setText("LogOut");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 630, 130, 40));

        jLabel13.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Laporan Harian", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 180, 180, 80));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Masukkan tanggal");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 200, -1, 20));

        jLabel15.setFont(new java.awt.Font("Forte", 1, 24)); // NOI18N
        jLabel15.setText("Data Laporan Donasi");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 114, 250, 40));
        getContentPane().add(txhari_kas, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 540, 120, 30));

        jLabel9.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Laporan Harian", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 500, 180, 80));

        txkas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Image 32pixel/printer.png"))); // NOI18N
        txkas.setText("Cetak Kas");
        txkas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txkasActionPerformed(evt);
            }
        });
        getContentPane().add(txkas, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 600, 130, 40));

        harian_donasi.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        harian_donasi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Image 32pixel/printer.png"))); // NOI18N
        harian_donasi.setText("Cerak Donasi");
        harian_donasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                harian_donasiActionPerformed(evt);
            }
        });
        getContentPane().add(harian_donasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, 150, 40));

        jLabel16.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Laporan Bulanan", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 160, 180, 120));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Masukkan tanggal");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 180, -1, -1));
        getContentPane().add(txbulanan_kas, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 510, 120, 30));
        getContentPane().add(txbulanan_kass, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 550, 120, 30));

        jLabel10.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Laporan Bulanan", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 470, 180, 120));

        bulanan_kas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Image 32pixel/printer.png"))); // NOI18N
        bulanan_kas.setText("Cetak Kas");
        bulanan_kas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bulanan_kasActionPerformed(evt);
            }
        });
        getContentPane().add(bulanan_kas, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 600, 130, 30));

        tanggal.setBackground(new java.awt.Color(255, 255, 255));
        tanggal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tanggal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Image 32pixel/calendar.png"))); // NOI18N
        tanggal.setText("Tanggal");
        getContentPane().add(tanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, -1, -1));
        getContentPane().add(txtbulan_penjualan, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 200, 130, 30));
        getContentPane().add(txtbulan_penjualann, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 240, 130, 30));

        jLabel4.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Laporan Bulanan", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 160, 180, 120));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Image 32pixel/printer.png"))); // NOI18N
        jButton1.setText("Cetak Penjualan");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 290, 150, 40));

        btsaran.setFont(new java.awt.Font("Gill Sans MT", 0, 17)); // NOI18N
        btsaran.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Image 32pixel/report.png"))); // NOI18N
        btsaran.setText("Saran");
        btsaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsaranActionPerformed(evt);
            }
        });
        getContentPane().add(btsaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 540, 110, 40));

        jButton6.setFont(new java.awt.Font("Gill Sans MT", 0, 17)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Image 32pixel/report.png"))); // NOI18N
        jButton6.setText("Ebout");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, 110, 40));

        jButton9.setFont(new java.awt.Font("Gill Sans MT", 0, 17)); // NOI18N
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Image 32pixel/report.png"))); // NOI18N
        jButton9.setText(" Data Laporan");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 470, 180, 40));

        jButton5.setFont(new java.awt.Font("Gill Sans MT", 0, 17)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Image 32pixel/cash-flow.png"))); // NOI18N
        jButton5.setText("STOK & KAS");
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton5.setDoubleBuffered(true);
        jButton5.setFocusCycleRoot(true);
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 410, 180, 40));

        jButton2.setFont(new java.awt.Font("Gill Sans MT", 0, 17)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Image 32pixel/money-transfer.png"))); // NOI18N
        jButton2.setText("TRANSAKSI");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 160, 40));

        jButton4.setFont(new java.awt.Font("Gill Sans MT", 0, 17)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Image 32pixel/data.png"))); // NOI18N
        jButton4.setText("MASTER");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 160, 40));

        btmenu.setFont(new java.awt.Font("Gill Sans MT", 0, 17)); // NOI18N
        btmenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Image 32pixel/home.png"))); // NOI18N
        btmenu.setText("MENU");
        btmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmenuActionPerformed(evt);
            }
        });
        getContentPane().add(btmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 160, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Image umum/Menu Laporan.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 720));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bulanan_donasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bulanan_donasiActionPerformed
        // TODO add your handling code here:

        Map<String,Object>param = new HashMap<String,Object>();
        param.put("tgl1",txdonasi.getText());
        param.put("tgl2",txdonasii.getText());
        try {
            String reportName = "src/Report/Bulanan_Donasi.jasper";
            JasperPrint jPrint = JasperFillManager.fillReport(reportName, param, Koneksi.configDB());
            JasperViewer.viewReport(jPrint, false);
        } catch (Exception e){
            System.out.println("gagal"+e);
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_bulanan_donasiActionPerformed

    private void txdonasiiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txdonasiiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txdonasiiActionPerformed

    private void harian_penjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_harian_penjualanActionPerformed
        // TODO add your handling code here:
        try {
            String reportName = "src/Report/Harian_Penjualan.jasper";
            HashMap parameter = new HashMap();
            parameter.put("tgl_penjualan",this.txhari_penjualan.getText());
            JasperPrint jPrint = JasperFillManager.fillReport(reportName, parameter,  Koneksi.configDB());
            JasperViewer.viewReport(jPrint, false);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_harian_penjualanActionPerformed

    private void txhari_donasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txhari_donasiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txhari_donasiActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        //          String ObjButtons[] = {"Yes","No"};
        // int pilihan = JOptionPane.showOptionDialog(null,"Apakah Anda Yakin Ingin keluar dari Aplikasi ?","Message",JOptionPane.DEFAULT_OPTION,JOptionPane.QUESTION_MESSAGE,null,ObjButtons,ObjButtons[1]);
        // if(pilihan == 0){
            new Login.Form_Login().setVisible(true);
            dispose();
            //        System.exit(0);

    }//GEN-LAST:event_jButton8ActionPerformed

    private void txkasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txkasActionPerformed
        // TODO add your handling code here:
           try {
            String reportName = "src/Report/Harian_Kas.jasper";
            HashMap parameter = new HashMap();
            parameter.put("tgl_kas",this.txhari_kas.getText());
            JasperPrint jPrint = JasperFillManager.fillReport(reportName, parameter,  Koneksi.configDB());
            JasperViewer.viewReport(jPrint, false);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_txkasActionPerformed

    private void harian_donasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_harian_donasiActionPerformed
        // TODO add your handling code here:
                try {
            String reportName = "src/Report/Harian_Donasi.jasper";
            HashMap parameter = new HashMap();
            parameter.put("tgl_donasi",this.txhari_donasi.getText());
            JasperPrint jPrint = JasperFillManager.fillReport(reportName, parameter,  Koneksi.configDB());
            JasperViewer.viewReport(jPrint, false);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_harian_donasiActionPerformed

    private void bulanan_kasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bulanan_kasActionPerformed
        // TODO add your handling code here:
        
        Map<String,Object>param = new HashMap<String,Object>();
        param.put("tgl_kas1",txbulanan_kas.getText());
        param.put("tgl_kas2",txbulanan_kass.getText());
        try {
            String reportName = "src/Report/Bulanan_Kas.jasper";
            JasperPrint jPrint = JasperFillManager.fillReport(reportName, param, Koneksi.configDB());
            JasperViewer.viewReport(jPrint, false);
        } catch (Exception e){
            System.out.println("gagal"+e);
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_bulanan_kasActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
                Map<String,Object>param = new HashMap<String,Object>();
        param.put("tgl1_penjualan",txtbulan_penjualan.getText());
        param.put("tgl2_penjualan",txtbulan_penjualann.getText());
        try {
            String reportName = "src/Report/Bulanan_Penjualan.jasper";
            JasperPrint jPrint = JasperFillManager.fillReport(reportName, param, Koneksi.configDB());
            JasperViewer.viewReport(jPrint, false);
        } catch (Exception e){
            System.out.println("gagal"+e);
            JOptionPane.showMessageDialog(null,e);
        }
                       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btsaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsaranActionPerformed
        // TODO add your handling code here:
        Form_Ebout_FeedBack.Form_FeedBack frm = new Form_Ebout_FeedBack.Form_FeedBack(this, rootPaneCheckingEnabled);
        frm.setTitle("Saran");
        frm.setVisible(true);
    }//GEN-LAST:event_btsaranActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        new Form_Ebout_FeedBack.Form_Ebout().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        new Output.Form_Tampilan_Laporan().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        new Proses.Form_Stok_Kas().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new Proses.Form_Transaksi().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        new Master.Form_Master().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmenuActionPerformed
        // TODO add your handling code here:
        new Master.Form_Menu_Utama().setVisible(true);
        dispose();
    }//GEN-LAST:event_btmenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Laporan_All.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Laporan_All.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Laporan_All.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Laporan_All.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Laporan_All().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btmenu;
    private javax.swing.JButton btsaran;
    private javax.swing.JButton bulanan_donasi;
    private javax.swing.JButton bulanan_kas;
    private javax.swing.JButton harian_donasi;
    private javax.swing.JButton harian_penjualan;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel tanggal;
    private javax.swing.JTextField txbulanan_kas;
    private javax.swing.JTextField txbulanan_kass;
    private javax.swing.JTextField txdonasi;
    private javax.swing.JTextField txdonasii;
    private javax.swing.JTextField txhari_donasi;
    private javax.swing.JTextField txhari_kas;
    private javax.swing.JTextField txhari_penjualan;
    private javax.swing.JButton txkas;
    private javax.swing.JTextField txtbulan_penjualan;
    private javax.swing.JTextField txtbulan_penjualann;
    // End of variables declaration//GEN-END:variables
}
